### ISSUE TITLE
I have some property about create shipping label API.

### ISSUE THREAD

**Issue by hatasum** [microsoft/SDCM#15]
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-shipping-label
I use create-a-new-shipping-label api to create shipping label, but have some UI property question as below.

1. What property means to choose the release date to "Publish my driver as soon as it passes certification"?
I try to set "publishingSpecifications:goLiveDate" to null, but UI still choose "No sooner than some date".

2. What property means to check yes for "I understand that selecting driver promotion overrides requires additional Microsoft evaluation and will add up to two weeks to my publication request."?

3. What property means to check yes for "I have reviewed Microsoft’s additional security measures and driver requirements when running Windows 10 S, and I confirm I have tested my driver in this configuration."?

Thank you.

**Comment by sfudally** [comment]
1 and 2 I believe are informational and passed to the team that manages driver publications.

3 should go with the publishToWindows10s property to make sure that you have validated the S Mode behavior.

**Comment by SillyKeith** [comment]
#1 "No sooner than some date".  is a No-OP  -  That functionality is not implemented.
