### ISSUE TITLE
Create shipping label get error.

### ISSUE THREAD

**Issue by hatasum** [Microsoft/SDCM#16]
We cannot create shipping label by API.
Return error : readOnlyProduct, Not allowed to create the shipping labels on a read only product.
But the product's permission is "Publisher", not "Read-only".

How to create shipping label which product's permission is "Publisher"?
Thank you.

**Comment by sfudally** [comment]
For this one, please submit the issue to HDC via the feedback page since the issue is in the service:
![image](https://user-images.githubusercontent.com/40132546/54883224-d9b5c880-4e20-11e9-9932-49db28ba4a7c.png)

**Comment by SillyKeith** [comment]
Do not submit support issues via Feedback.  Unfortunately that area is not being monitored.  Instead, you should submit bugs/questions/issues via a Support Ticket
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-dashboard-faq

How do I contact Partner Center Support?
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: https://developer.microsoft.com/windows/support. Select Contact us, Dashboard issue, and then Hardware submissions & signing (all OS version) from the dropdown.

**Comment by hatasum** [comment]
Thanks your reply.
I apologize for the inconvenience.
