### ISSUE TITLE
I cannot sign driver by script Attestation.ps1 

### ISSUE THREAD

**Issue by KSBE** [microsoft/SDCM#20]
Log from output:

Attestation Submission 
> Create Product
    * Create JSON
    * Submit
Did not find product ID 
SurfaceDevCenterManager v1.0.0.0
> Create Option
ERROR (DevCenterErrorDetails)
Code:    503 ServiceUnavailable
HttpCode:503
Message: Service Unavailable

**Comment by sfudally** [comment]
Did you set up authconfig.json?

**Comment by KSBE** [comment]
Yep.
If i didn't set up authconfig.json then I was got next error

PS C:\Users\test\Release> .\Attestation.ps1 'TestProductName' 'WINDOWS_v100_X64_RS3_FULL' ..\test.cab 
Attestation Submission 

> Create Product  
    * Create JSON 
    * Submit 
Did not find product ID 
SurfaceDevCenterManager v1.0.0.0 
Error Parsing Options: Unable to get Dev Center Credentials
Correlation Id: 739abf15-5273-4285-ac46-cae560c106a5
Return: -4 (NO_DEV_CENTER_CREDENTIALS_FOUND)
-1

**Comment by sfudally** [comment]
I tried a test just now and that went through ok.  Do you have permissions on HDC to do submissions for your account that you set up?

**Comment by KSBE** [comment]
Thanks,
I resolved this issue, azure application should be have permission in partner center.
This permission can be applied only from partner center.
