### ISSUE TITLE
SDCM : Field not found Exception

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#36]
> Create Product
    * Create JSON
    * Submit
    * PID: 14269363839993683
> Create Submission
    * Create JSON
    * Submit
    * SID: 1152921505694771210
> Upload File
SurfaceDevCenterManager v1.0.0.1
> Upload Option
> Fetch Submission Info
> initialPackage Url: https://ingestionpackagesprod1.blob.core.windows.net/ingestion/3a0a7815-4afc-4ec3-b394-c0caf46446a1?sv=2018-03-28&sr=b&sig=0u%2B1Xyy780pHn3
LlwIyPU8zaLRj%2BSr7EUzfBOSrBJwY%3D&se=2022-04-25T14:31:15Z&sp=rwl&rscd=attachment%3B filename%3Dinitial_1152921505694771210.cab
> Uploading Submission Package
100%
Correlation Id: 988337c4-358f-4b9d-b98d-77221a68c1d2
Return: 0 (SUCCESS)
> Commit Submission
SurfaceDevCenterManager v1.0.0.1
> Commit Option
> Sending Commit
Unhandled Exception:
System.MissingFieldException: Field not found: 'Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterErrorDetails.Trace'.
   at SurfaceDevCenterManager.Program.DevCenterErrorDetailsDump(DevCenterErrorDetails error)
   at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:lin
e 417
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SurfaceDevCenterManager.Program.Main(String[] args) in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:line 60
Last Command:

Unhandled Exception: System.MissingFieldException: Field not found: 'Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterErrorDetails.Trace'.
   at SurfaceDevCenterManager.Program.DevCenterErrorDetailsDump(DevCenterErrorDetails error)
   at SurfaceDevCenterManager.Program.Main(String[] args) in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:line 67
> Wait for Submission to complete
    * Dev Center URL: https://developer.microsoft.com/en-us/dashboard/hardware/driver/14269363839993683
    * PID: 14269363839993683
    * SID: 1152921505694771210
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  finalizeIngestion
> State: completed
> signedPackage Url: https://ingestionpackagesprod1.blob.core.windows.net/ingestion/5d3b426b-c381-423d-8b69-f6ef9de6c201?sv=2018-03-28&sr=b&sig=8d6nE1bQFWXdTSjNj
UBh%2BMpO3YRlWZWASb2fIqMXfgE%3D&se=2022-04-25T00:07:42Z&sp=rl&rscd=attachment%3B filename%3DSigned_1152921505694771210.zip
> driverMetadata Url: https://prodingestionimage1.blob.core.windows.net/ingestion/e8ffe6f8-72f9-4029-8f0d-130d8e754d3b?sv=2018-03-28&sr=b&sig=iu%2Fl%2BbZJ7kDZxWI
j9snIyV%2FBCpgvV6TEeMOdMF%2B44ng%3D&se=2022-04-25T00:07:42Z&sp=rl&rscd=attachment%3B filename%3DdriverMetadata_1152921505694771210.json
> Submission Ready
> Done
Correlation Id: 0c495192-ccdd-4ea3-9f89-6876456d5a05
Return: 0 (SUCCESS)
> Download File
SurfaceDevCenterManager v1.0.0.1
> Download Option ./DRIVER_sign/MT7961X64.cab.signed.zip
> Fetch Submission Info
> signedPackage Url: https://ingestionpackagesprod1.blob.core.windows.net/ingestion/5d3b426b-c381-423d-8b69-f6ef9de6c201?sv=2018-03-28&sr=b&sig=xwl4lt4gP7ye3vuMC
WYV20fETbNDMVrN0DEfXzGLVdk%3D&se=2022-04-25T00:07:45Z&sp=rl&rscd=attachment%3B filename%3DSigned_1152921505694771210.zip
100%
Correlation Id: 765d6c4f-5f83-44a9-a64e-d73fe178391e

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, thank you for opening the issue and providing the console readout. Looks like we have two issues here. One for this project `SDCM` and one with the consumed package `Microsoft.Devices.HardwareDevCenterManager`.

- `Microsoft.Devices.HardwareDevCenterManager` package is missing the `Trace` field in the `DevCenterErrorDetails` when this scenario occurred.
Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterErrorDetails.`Trace`

- `SurfaceDevCenterManager` is not handling the missing field in the `DevCenterErrorDetailsDump(DevCenterErrorDetails error)` method.

We will get this looked at and keep you updated. Were you able to retry the run with success?

**Comment by MTKSDCM** [comment]
Yes, for some scenarios it is working without any issue, fail rate 3/10.

**Comment by MTKSDCM** [comment]
> Create Product
    * Create JSON
    * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option

============================================================
        SurfaceDevCenterManager Exception Log
Option:          CreateOption
Section:         NewProduct
Type:            Microsoft.Devices.HardwareDevCenterManager.Utility.HttpRetriesExhaustedException
Message:         AuthorizationHandler: NULL response, unable to talk to HDC
Inner Exception:
Correlation Id:  9b1dce11-4c6e-4197-849a-eab7bc8ec694
============================================================

Correlation Id: 9b1dce11-4c6e-4197-849a-eab7bc8ec694
Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION)
-1

**Comment by MTKSDCM** [comment]
i am getting above error code for each submission 
Earlier there were failure but it was signing for some submission.

**Comment by Ben-Carpenter** [comment]
> > Create Product
> > * Create JSON
> > * Submit
> > Did not find product ID
> > SurfaceDevCenterManager v1.0.0.1
> > Create Option
> 
> # ============================================================
> SurfaceDevCenterManager Exception Log
> Option: CreateOption
> Section: NewProduct
> Type: Microsoft.Devices.HardwareDevCenterManager.Utility.HttpRetriesExhaustedException
> Message: AuthorizationHandler: NULL response, unable to talk to HDC
> Inner Exception:
> Correlation Id: 9b1dce11-4c6e-4197-849a-eab7bc8ec694
> Correlation Id: 9b1dce11-4c6e-4197-849a-eab7bc8ec694 Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION) -1

This is a separate issue from the `System.MissingFieldException: Field not found:` . Could you please open in a new issue?
