### ISSUE TITLE
Unable to communicate to HDC issue

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#37]
> Create Product
    * Create JSON
    * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option

        SurfaceDevCenterManager Exception Log
Option:          CreateOption
Section:         NewProduct
Type:            Microsoft.Devices.HardwareDevCenterManager.Utility.HttpRetriesExhaustedException
Message:         AuthorizationHandler: NULL response, unable to talk to HDC
Inner Exception:
Correlation Id:  9b1dce11-4c6e-4197-849a-eab7bc8ec694

Correlation Id: 9b1dce11-4c6e-4197-849a-eab7bc8ec694
Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION)
-1

**Comment by Ben-Carpenter** [comment]
@MTKSDCM,  adding your comment over from other issue #36 

i am getting above error code for each submission
Earlier there were failure but it was signing for some submission.

**Comment by Ben-Carpenter** [comment]
@MTKSDCM , sounds like you were not able to connect to Partner Center (aka HDC). 
- Verify your credentials are valid and that you can reach their service.
- If this is an account issue please reach out to Partner Center directly.

Here is where the error is being thrown from the [`Microsoft.Devices.HardwareDevCenterManager`](https://github.com/microsoft/devices-hardware-dev-center-manager/blob/90a492ccb413fcc8ff355a9da3d613daaad3ef00/src/Microsoft.Devices.HardwareDevCenterManager/Utility/AuthorizationHandler.cs#L120) package.

**Comment by MTKSDCM** [comment]
@Ben-Carpenter, I have identified, this was due to some firewall restriction. changed the firewall setting now able to submit

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, thank you for confirming and responding. I will go ahead and close this issue.
