### ISSUE TITLE
Hardware>File Signing Service submission automation (testHarness LSA)

### ISSUE THREAD

**Issue by alastorid** [microsoft/SDCM#38]
Hello team!
Currently, LSA file signing cases are submitted manually via the web service (Hardware>File Signing Service):
`https://partner.microsoft.com/en-us/dashboard/hardware/FileSign/NewLSA`
Seeing that `Attestation.ps1` and `HLKx.ps1` are able to automate product related submissions.
May I know if there is a chance to see that the File Sign submission can also be automated?

Much Thanks!

**Comment by Ben-Carpenter** [comment]
@alastorid, are you asking if LSA signing can be requested with automation? 

Currently, LSA signing is only available in the Partner Center dashboard UI. In the [Product resource](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#product-resource) documentation, check out the available options for `testHarness`.

**Comment by amenefus** [comment]
Imagine 3 years later and STILL NO API!
