### ISSUE TITLE
SDCM failing to get Product ID

### ISSUE THREAD

**Issue by MansiBharadwaj** [microsoft/SDCM#42]
I followed the prerequisite steps properly and have given the clientID, key and tenentID but when executing the command to get product id it is failing with http error code 412 and saying evcertificate not found.
Why is this happening ?
I have given the client_secret then why it asking for certificate and if its required then where I have to add as there is no where mentioned about the certificate other than for .cab or .hlkx package.

Response: -
SurfaceDevCenterManager v1.0.0.1
> Create Option
ERROR (DevCenterErrorDetails)
Code:    evCertificateNotFound
HttpCode:412
Message: EV Certificate expired or not present
Correlation Id: 14d9929e-e497-4739-b40c-ace5aa9a52e2
Correlation Id: 14d9929e-e497-4739-b40c-ace5aa9a52e2
Return: -7 (NEW_PRODUCT_API_FAILED)

**Comment by Ben-Carpenter** [comment]
@MansiBharadwaj , I see you self closed this issue already. Did you figure out what the issue was? If so could you share for others who might encounter this in the future.

**Comment by MansiBharadwaj** [comment]
Well the issue was because the evcertificate from our backend side got expired. We fixed that and it gets solved

**Comment by Ben-Carpenter** [comment]
Ah yes, the `EV` certificate needed for your account under `Home / Account settings / Manage certificates`.
Sorry I didn't catch that initially. Thanks for updating the thread.
