### ISSUE TITLE
Getting error as "COMMAND_LINE_OPTION_PARSING_FAILED"

### ISSUE THREAD

**Issue by MansiBharadwaj** [microsoft/SDCM#52]
**Describe the bug**
The sdcm tool has returned this error when I retried to submit the package "COMMAND_LINE_OPTION_PARSING_FAILED "

**To Reproduce**
Its an uncertain behavior didn't get every time but 1-2 times I get this when retrying to submit the package in partner center using sdcm tool   

**Expected behavior**
Does not happen like this

**Desktop (please complete the following information)**
 - OS: windows server 2019

**Additional context**
Can anybody help to know why this occurred and how I can solve this!

**Comment by Ben-Carpenter** [comment]
@MansiBharadwaj could you please provide the argument(s) you are passing as defined in [Create a Submission](https://github.com/microsoft/SDCM#create-a-submission). Please obfuscate any identifiable values.

**Comment by MansiBharadwaj** [comment]
@Ben-Carpenter 
{
  "createType": "submission",
  "createSubmission": {
    "name": "$ProductName`_Attestation_Submission",
    "type": "initial"
  }
}
I have used this tool thousand times before but this error I observed first time.

**Comment by MBharadwaj23** [comment]
yes, this only I passed and it's not like I am using the tool first time I used it before 1000 times but this time when submission request failed, I retried three times and, in the end, I got this error.

**Comment by MansiBharadwaj** [comment]
yes, this only I passed and it's not like I am using the tool first time I used it before 1000 times but this time when submission request failed, I retried three times and, in the end, Got error
For example: - sdcm.exe -create "path to Json" -productid "id" :: id I got after the product submission.

**Comment by Ben-Carpenter** [comment]
Are you blocked or just reporting that it happened but were able to get it to run successfully?

**Comment by MBharadwaj23** [comment]
I am not blocked
I am just reporting because I also need to find a solution so this problem will not occur or if occur I will be able to handle but dont know how to handle

**Comment by MansiBharadwaj** [comment]
I am not blocked
I am just reporting because I also need to find a solution so this problem will not occur or if occur I will be able to handle but dont know how to handle

**Comment by Ben-Carpenter** [comment]
Alright, glad to hear you're not blocked. You can always try debugging the `args` being passed in.

This error is thrown [here](https://github.com/microsoft/SDCM/blob/3753f3df826c6f7f0f3b7fce0e9ddb9bb1bf45d9/SurfaceDevCenterManager/Program.cs#L154) at the beginning of the program when it parses the provided `args`.

`COMMAND_LINE_OPTION_PARSING_FAILED`

I will go ahead and close this issue.
