### ISSUE TITLE
SDCM.exe returns 0 without the download of the attestation signed driver download info (url)

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#53]
**Describe the bug**
SDCM.exe returns 0 without the download of the attestation signed driver download info (url)

**To Reproduce**
Run the script which uses attestation.ps1.

**Expected behavior**
The sdcm.exe should return success only after the download complete.

**Desktop (please complete the following information)**
 - OS: Windows server 2012
 - Version 

**Additional context**
Submission logs:
Correlation Id: b9afe90e-e573-4718-aa6f-4a8689c07718
Return: 0 (SUCCESS)
[07/06/23 18:49:50] Upload file done
[07/06/23 18:49:50] > Commit Submission
SurfaceDevCenterManager v1.0.0.1
> Commit Option
> Sending Commit
> Commit OK
Correlation Id: 6037fd36-34ec-4528-bb06-6d59ac750cba
Return: 0 (SUCCESS)
[07/06/23 18:49:57] Commit done
> Wait for Submission to complete
    * Dev Center URL: https://developer.microsoft.com/en-us/dashboard/hardware/driver/SID(Removed the SID value)
    * PID: Removed due to privacy
    * SID: Removed due to privacy
    * Start sleeping for 20 mins
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Retrying in 10 seconds...
SurfaceDevCenterManager v1.0.0.1
> Wait Option
> Step:  packageInfoValidation
> State: started
Execution timed out after 10 seconds.
Execution timed out with exit code ''.
Reached the maximum number of retries.
[07/06/23 19:19:47] Submission complete
> Download File
SurfaceDevCenterManager v1.0.0.1
> Download Option ../MTKSIGN_V2/One_File/file_x64.cab.signed.zip
> Fetch Submission Info
Correlation Id: 234134ce-4e0e-4b28-a6a2-05b44ad78cc8
Return: 0 (SUCCESS)
[07/06/23 19:19:50] Download complete
> Done
    * Output: ../MTKSIGN_V2/One_File/file_x64.cab.signed.zip
E:Didn't get MSFT signed zip file for free
bt_error_level=2

**Comment by Ben-Carpenter** [comment]
@mtksdcm, sorry to hear it was unsuccessful. Is this the first time it's happened? Thanks for the log, it does help to see the details.

Were you able to run the `download` command to get your files? We want to be sure you are not blocked.

**Comment by MTKSDCM** [comment]
@Ben-Carpenter, No it did not download the signed binary but we download them from partner center directly.
May i know what could be the possible reason for this issue.

**Comment by Ben-Carpenter** [comment]
@mtksdcm, try using the download command and let me know if there is an issue using it. For why it didn't work in your above scenario, I am not sure.

[Download files from a Submission](https://github.com/microsoft/SDCM#download-files-from-a-submission)
sample: `sdcm.exe -download hlksigned.zip -productid PID -submissionid SID`

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, if you are no longer experiencing this issue, I will go ahead and close. Please reopen if you continue to experience this issue. Thanks for creating and providing feedback!
