### ISSUE TITLE
Getting -429 http limit exceeded error for attestation signing request 

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#54]
**Describe the bug**
When we are trying to submit a attestation signing request by using sdcm.exe then we are getting http limit exceeded error 
**To Reproduce**
Submit the driver binaries using sdcm.exe

**Expected behavior**
It should sign the driver with any error.

**Desktop (please complete the following information)**
 - OS: [windows server 2012]
 -

**Additional context**
Attestation Submission

[08/17/23 22:37:26] > Create Product
    * Create JSON
    * Submit
[08/17/23 22:37:28] Create Product done
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option
CreateOption NewProduct experienced a HTTP 429 Too Many Requests response.
Correlation Id: 92519a17-8a89-446e-968e-7ccac4225a19
Return: -429 (HTTP_429_RATE_LIMIT_EXCEEDED)

May i know the possible reason for this failure?.

**Comment by Ben-Carpenter** [comment]
Hey @MTKSDCM, Partner Center APIs have a rate limit (per minute) for clients calling their APIs. You would need to check with Partner Center Support to see what that limit is for your account.

**Comment by MTKSDCM** [comment]
Hi @Ben-Carpenter, This limit is for API or account.

**Comment by Ben-Carpenter** [comment]
This limit is based on their API, called throttling or rate limiting. The API will respond with an `HTTP429` message. When `SDCM` gets this response from the API it will display the message and error code [HTTP_429_RATE_LIMIT_EXCEEDED](https://github.com/microsoft/SDCM/blob/3753f3df826c6f7f0f3b7fce0e9ddb9bb1bf45d9/SurfaceDevCenterManager/ErrorCodes.cs#L60) and return.

Create product command checks for `HTTP429` [here](https://github.com/microsoft/SDCM/blob/3753f3df826c6f7f0f3b7fce0e9ddb9bb1bf45d9/SurfaceDevCenterManager/Program.cs#L232) in the tool and then logs it to the console. You'll see this check throughout the various commands.

MDN Docs HTTP429 - [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) 

Their API service I believe allows around 30 calls /minute and subject to change as they see fit to keep their service balanced and available for all partners.

If you are using scripts to run these commands, you should be able to check for the `SDCM` return message and `retry` the call programmatically.

**Comment by Ben-Carpenter** [comment]
I will close this issue for now, please reopen or create a new issue if needed.
