### ISSUE TITLE
PARTNER_CENTER_HTTP_EXCEPTION

### ISSUE THREAD

**Issue by hosamanisachin** [microsoft/SDCM#55]
Hello,
@Ben-Carpenter 

Please pardon me if I am asking my question at the wrong place, and if there is a forum to discuss please let me know.

Issue: 

> Create Product
    * Create JSON
    * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option

============================================================
        SurfaceDevCenterManager Exception Log
Option:          CreateOption
Section:         NewProduct
Type:            System.OperationCanceledException
Message:         The operation was canceled.
Inner Exception:
Correlation Id:  75e55278-3819-49dd-8dbe-d87ffe8ed34b
============================================================

Correlation Id: 75e55278-3819-49dd-8dbe-d87ffe8ed34b
Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION)
-1

SDCM Version: SurfaceDevCenterManager v1.0.0.1

I am not able to identify what went wrong in this process. The error code -1000 does not take me to any solution that I should follow and correct myself. Is this something to do with the client key that I have added(It has been 6 months) ?

**Comment by Ben-Carpenter** [comment]
Hello @hosamanisachin, it looks like the exception was caught in the create product [section](https://github.com/microsoft/SDCM/blob/3753f3df826c6f7f0f3b7fce0e9ddb9bb1bf45d9/SurfaceDevCenterManager/Program.cs#L251).

There are a few things that might cause this to happen. Please check the following. 
(Forgive the following, I assume nothing, so I will cover the steps).

1. [ ] You have registered your AAD client app in Partner Center. [Complete the prerequisites for using the Microsoft Hardware API](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/dashboard-api#complete-the-prerequisites-for-using-the-microsoft-hardware-api)
1. [ ] Your client app has the correct permissions (Driver Submitter). [Assigning the appropriate Hardware roles to your Microsoft Entra Identity application](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/dashboard-api#assigning-the-appropriate-hardware-roles-to-your-microsoft-entra-identity-application)
1. [ ] Your client credentials are correct and valid (tenantId, clientId, client key (or secret)).
1. [ ] Check that you are getting a valid token used to make the API call. [Obtain an Microsoft Entra Identity access token](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/dashboard-api#obtain-an-microsoft-entra-identity-access-token)
1. [ ] All properties in the [authconfig.json](https://github.com/microsoft/SDCM/blob/main/SurfaceDevCenterManager/authconfig.json) are correct.
1. [ ] The output from either [Scripts/Attestation.ps1](https://github.com/microsoft/SDCM/blob/main/Scripts/Attestation.ps1) or [Scripts/HLKx.ps1](https://github.com/microsoft/SDCM/blob/main/Scripts/HLKx.ps1)is correct.
1. [ ] You are submitting a cab file with the correct signatures.

If all items above are valid, and you have verified you are able to run other commands successfully then other issues might have occurred from the Partner Center API service.
1. Transient errors
1. The API service experienced interruptions (HTTP500)

> If this is an internal question, please use the appropriate channels outlined by your team.

**Comment by hosamanisachin** [comment]
Hello,
@Ben-Carpenter

I had expired client secret. To which after renewing got it working.

Thank you very much for the above mentioned steps to follow for debugging. 
I would please request you to keep this general debug steps to be followed for everyone.

Thank you.

**Comment by hosamanisachin** [comment]
Another point I would like to add is that, when I tried this from REST API(Using Postman utility). I was able to get a descriptive information of the key being expired.

"error": "invalid_client",
   "error_description": "AADSTS7000222: The provided client secret keys for app 'abcd' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.\r\nTrace ID: xyz\r\nCorrelation ID: 15dc7d79-d6e0-4408-aac7-fe3fca50c74b\r\nTimestamp: BACKTOTHEFUTURE",

@Ben-Carpenter 
Is there any chance we can capture this description and get it printed to the console?

**Comment by Ben-Carpenter** [comment]
@hosamanisachin
Yes, we'll look at [DevCenterErrorDetailsDump](https://github.com/microsoft/SDCM/blob/3753f3df826c6f7f0f3b7fce0e9ddb9bb1bf45d9/SurfaceDevCenterManager/Program.cs#L1176C29-L1176C54) and see why the additional details were not provided.
