### ISSUE TITLE
Auth failure (Microsoft.Azure.Storage.StorageException) on Upload Submission to Partner Center

### ISSUE THREAD

**Issue by tedops** [microsoft/SDCM#59]
**Describe the bug**
As of yesterday, SDCM has been returning an auth failure with the following text:
```
============================================================
	SurfaceDevCenterManager Exception Log
Option:          SubmissionPackagePath
Section:         GetSubmission
Type:            Microsoft.Azure.Storage.StorageException
Message:         Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Inner Exception: 
Correlation Id:  [redacted]
============================================================
```
There have been no changes to our account or automation. Our automated jobs have begun failing and investigating the failures has uncovered this error.

**To Reproduce**
Execute HLKx.ps1 script with all expected parameters and ensure the referenced file exists.

**Expected behavior**
The upload is accepted without error and the signing process continues as normal. This has been faithfully running for over a year without error or human intervention.

**Desktop (please complete the following information)**
 - OS: Win 8
 - Version 1.0.0.1 (release 1.2023.221.1)

Has any change happened on the Partner Center/API side to require a differently formatted auth header? Looking through the past 2 releases, there doesn't seem to be any code change made needing to account for this.

Thank you!

**Comment by Ben-Carpenter** [comment]
@tedops, please grab the latest release from today, `1.2024.911.1` and let us know if you are still experiencing the same issue.

**Comment by Ben-Carpenter** [comment]
> @tedops, please grab the latest release from today, `1.2024.911.1` and let us know if you are still experiencing the same issue.

The auth here is regarding to the Azure storage and URI. There was an update to the Dashboard API service which required package updates for `BlobStorage`. The update is in release `1.2024.911.1`.

If you could, please confirm the fix. I will close this issue after confirmation or end of day if we don't hear back.

**Comment by tedops** [comment]
@Ben-Carpenter upgrading to 1.2024.911.1 fixed the issue. I'm curious as to what Microsoft changed to force that header, however I can confirm that rebuilding SDCM did the trick. Thank you.

**Comment by Ben-Carpenter** [comment]
> @Ben-Carpenter upgrading to 1.2024.911.1 fixed the issue. I'm curious as to what Microsoft changed to force that header, however I can confirm that rebuilding SDCM did the trick. Thank you.


> @Ben-Carpenter upgrading to 1.2024.911.1 fixed the issue. I'm curious as to what Microsoft changed to force that header, however I can confirm that rebuilding SDCM did the trick. Thank you.

Thanks for confirming. See my previous reply to you regarding the change for `BlobStorage`.
