### ISSUE TITLE
Http retries Exhausted Exception while sending signing request

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#62]
**Describe the bug**

> Create Product
    * Create JSON
    * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option

============================================================
        SurfaceDevCenterManager Exception Log
Option:          CreateOption
Section:         NewProduct
**Type:            Microsoft.Devices.HardwareDevCenterManager.Utility.HttpRetriesExhaustedException
Message:         AuthorizationHandler: NULL response, unable to communicate with Hardware Dev Center
Inner Exception:
Correlation Id:  ***
============================================================

Correlation Id: ***
Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION)**

**To Reproduce**
Run latest SDCM tool

**Expected behavior**
SIgn should success.

**Desktop (please complete the following information)**
 - OS: [e.g. win10] : Windows server 2022
 - Version [e.g. 22] : 20348.350

**Additional context**
May i know what could be the possible issue and how can we mitigate it .

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, which `-creds` [option](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Program.cs#L136) are you passing in your command? Please use the following for each scenario.

```shell
sdcm.exe -creds ???? create product -productid 123456789
```

For all options below, these `common` key-value pairs are needed either in `environment variable` or in the `authconfig.json` file depending on which credential option you are using.
| Auth Config File | Environment Variables |
|---|---|
| `tenantId` | `SDCM_CREDS_TENANTID` |
| `clientId` | `SDCM_CREDS_CLIENTID` | 
| `url` | `SDCM_CREDS_URL` |
| `urlPrefix` | `SDCM_CREDS_URLPREFIX` |

| Credential Type | `-creds` Option | Credential Reference | Values to Use | Notes
|---|---|---|---|---|
| Managed Identity | ManagedIdentity |  [ManagedIdentity](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L132) | `common` + `SDCM_CREDS_MI_CLIENTID`, `SDCM_CREDS_MI_SCOPE` | Set `environment variables` + `Federated Credential` needs to be set in app registration. | 
| Managed Identity | MiThenFile |  [MiThenFile](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L151) | `common` + `managedIdentityClientId`, `scope` | Use `authconfig.json` file + `Federated Credential` needs to be set in app registration.  | 
| Client Credentials | ENVOnly | [ENVOnly](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L98) |  `common` + `SDCM_CREDS_KEY` | `Environment variables` need to be set. |
| Client Credentials | ClientCredentials | [ClientCredentials](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L98) | `common` + `SDCM_CREDS_KEY` | Client `secret` needs to be valid in app registration. |
| File Only |  FileOnly | [FileOnly](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L178) | `common` + the other values from previous options in this table. | Use `authconfig.json` file. Ensure `environment variables` and/or app registration has the correct values from previous options above depending on which `-creds` option you are trying to use.|

**Comment by Ben-Carpenter** [comment]
Please let us know if you need further help. If nothing else is needed, please close the issue. I will get my previous reply into the `README`.

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, would you mind if we updated the title of this issue to `AuthorizationHandler: NULL response, unable to communicate with Hardware Dev Center`

**Comment by MTKSDCM** [comment]
previously i never passed such credential in command, i just used  authconfig.json for credentials

**Comment by MTKSDCM** [comment]
Is it mandatory now to pass this option ?
and because of this i am getting this error

**Comment by Ben-Carpenter** [comment]
> Is it mandatory now to pass this option ? and because of this i am getting this error

It's not mandatory. If you don't pass a credential it defaults to `AADThenFile`.  This will try [GetWebApiCreds](https://github.com/microsoft/SDCM/blob/8d8bc16691c39ecac2db90bbb72721d51dd2a35b/SurfaceDevCenterManager/Utility/DevCenterCredentialsHandler.cs#L206) if `creds` is null it will read the `authconfig.json` file.

Only populate the values for the credential option you want to use.

If you are using client credentials, your json should look like this.
```json
[
  {
    "tenantId": "guid",
    "clientId": "guid",
    "managedIdentityClientId": "guid", // remove or leave as empty string
    "scope":  "string", // remove or leave as empty string
    "key": "string",
    "url": "https://manage.devcenter.microsoft.com",
    "urlPrefix": "v2.0/my"
  }
]
```

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, checking back to make sure you were able to get things working.

**Comment by Ben-Carpenter** [comment]
> @MTKSDCM, checking back to make sure you were able to get things working.

@MTKSDCM, please let us know if you are still having issues or were able to resolve. If we don't hear back by EOW we will close the issue.

**Comment by MTKSDCM** [comment]
Still getting this issue on one windows server.
 Attestation Submission
[2024-09-20 09:50:35] [build-stdout] > Create Product
[2024-09-20 09:50:35] [build-stdout]     * Create JSON
[2024-09-20 09:50:35] [build-stdout]     * Submit
[2024-09-20 09:50:40] [build-stdout]     * PID: 13990390021569011
[2024-09-20 09:50:40] [build-stdout] > Create Submission
[2024-09-20 09:50:40] [build-stdout]     * Create JSON
[2024-09-20 09:50:40] [build-stdout]     * Submit
[2024-09-20 09:50:42] [build-stdout] Did not find submission ID
[2024-09-20 09:50:42] [build-stdout] SurfaceDevCenterManager v1.0.0.1
[2024-09-20 09:50:42] [build-stdout] > Create Option
[2024-09-20 09:50:42] [build-stdout] > Creating Submission
[2024-09-20 09:50:42] [build-stdout] CreateOption NewSubmission experienced a HTTP 429 Too Many Requests response.
[2024-09-20 09:50:42] [build-stdout] Correlation Id: 9a5c1401-2de1-4dac-a8ee-97518e753024
[2024-09-20 09:50:42] [build-stdout] Return: -429 (HTTP_429_RATE_LIMIT_EXCEEDED)
[2024-09-20 09:50:42] [build-stdout] -1

**Comment by Ben-Carpenter** [comment]
> Still getting this issue on one windows server. Attestation Submission [2024-09-20 09:50:35] [build-stdout] > Create Product [2024-09-20 09:50:35] [build-stdout] * Create JSON [2024-09-20 09:50:35] [build-stdout] * Submit [2024-09-20 09:50:40] [build-stdout] * PID: 13990390021569011 [2024-09-20 09:50:40] [build-stdout] > Create Submission [2024-09-20 09:50:40] [build-stdout] * Create JSON [2024-09-20 09:50:40] [build-stdout] * Submit [2024-09-20 09:50:42] [build-stdout] Did not find submission ID [2024-09-20 09:50:42] [build-stdout] SurfaceDevCenterManager v1.0.0.1 [2024-09-20 09:50:42] [build-stdout] > Create Option [2024-09-20 09:50:42] [build-stdout] > Creating Submission [2024-09-20 09:50:42] [build-stdout] CreateOption NewSubmission experienced a HTTP 429 Too Many Requests response. [2024-09-20 09:50:42] [build-stdout] Correlation Id: 9a5c1401-2de1-4dac-a8ee-97518e753024 [2024-09-20 09:50:42] [build-stdout] Return: -429 (HTTP_429_RATE_LIMIT_EXCEEDED) [2024-09-20 09:50:42] [build-stdout] -1

Glad to hear you were able to get past your `auth` issue. We can close this issue #62

For the `HTTP 429`, you are making too many calls to the Partner Center APIs within your allowed rate per minute. You will need to handle that separately. Try a delay between your calls. If you are using multiple machines or instances with the same client ID, you will need to keep that in mind.

Looks like your `Submission` might have had an issue with `submit` based on the `Did not find submission ID`.  Check partner center for any error details.
