### ISSUE TITLE
Submission package upload failure

### ISSUE THREAD

**Issue by fdagnew** [microsoft/SDCM#63]
Hi SDCM team,

I am experiencing an issue while using SDCM tool to upload a submission package for TDT driver. 
Below are the details 

**Describe the bug**
While attempting to upload the submission package for the TDT driver, an error occurs (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)

**To Reproduce**
Steps to reproduce the behavior.
1. Run the following command to create the driver
      sdcm.exe -create c\path\to\Create_TDT_Driver_HLK.json
   
2. Run the command to create the submission
      sdcm.exe -create c\path\to\Create_TDT_Driver_Submission_HLK.json -productid <ProductID>
   
3. Run the command to upload the signed package
      sdcm.exe -upload <signed_package>.hlkx -productid <ProductID> -submissionid <SubmissionID>
   

**Expected behavior**
The submission package should upload successfully without failure

 sdcm.exe -upload <signed_package>.hlkx -productid <ProductID> -submissionid <SubmissionID>

Error message  

SurfaceDevCenterManager v1.0.0.1

> Upload Option
> Fetch Submission Info
> initialPackage Url: <initialPackageUrl>
> Uploading Submission Package
============================================================
SurfaceDevCenterManager Exception Log
Option:          SubmissionPackagePath
Section:         GetSubmission
Type:            Microsoft.Azure.Storage.StorageException
Message:         Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Inner Exception:
Correlation Id:  *****-***-*****-755863219cfc
Return: -1000 (PARTNER_CENTER_HTTP_EXCEPTION)

**Desktop (please complete the following information)**
- HLK OS: Windows Server 2019

**Additional context**

The error log indicates a failure in authenticating the request. Correlation ID: *****-***-*****-755863219cfc

**Comment by fdagnew** [comment]
I am getting this error - 

C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager>dotnet --list-sdks
8.0.403 [C:\Program Files\dotnet\sdk]

C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager>dotnet build
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(6,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft'
(are you missing an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(7,17): error CS0234: The type or namespace name 'IdentityModel' does not exist in the namespace 'Micro
soft' (are you missing an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(8,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a usin
g directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(6,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(7,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(8,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(9,7): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly referen
ce?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(10,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly
reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(36,16): error CS0246: The type or namespace name 'NewProduct' could not be found (are you missing a using directive or an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(81,43): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(39,16): error CS0246: The type or namespace name 'NewSubmission' could not be found (are you missing a using directive or an assem
bly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(42,16): error CS0246: The type or namespace name 'NewShippingLabel' could not be found (are you missing a using directive or an as
sembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(1140,38): error CS0246: The type or namespace name 'OptionSet' could not be found (are you missing a using directive or an assembl
y reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(1174,55): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive o
r an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(50,24): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(32,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(32,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(35,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(35,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(38,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(38,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(41,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(41,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(88,39): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
(are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(206,40): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(304,40): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(325,48): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]

Build FAILED.

C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(6,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft'
(are you missing an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(7,17): error CS0234: The type or namespace name 'IdentityModel' does not exist in the namespace 'Micro
soft' (are you missing an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(8,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a usin
g directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(6,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(7,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(8,17): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft' (are you missing an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(9,7): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly referen
ce?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(10,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly
reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(36,16): error CS0246: The type or namespace name 'NewProduct' could not be found (are you missing a using directive or an assembly
 reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(81,43): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(39,16): error CS0246: The type or namespace name 'NewSubmission' could not be found (are you missing a using directive or an assem
bly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(42,16): error CS0246: The type or namespace name 'NewShippingLabel' could not be found (are you missing a using directive or an as
sembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(1140,38): error CS0246: The type or namespace name 'OptionSet' could not be found (are you missing a using directive or an assembl
y reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(1174,55): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive o
r an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(50,24): error CS0246: The type or namespace name 'DevCenterErrorDetails' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(32,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(32,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(35,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(35,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(38,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(38,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(41,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or
an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Program.cs(41,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(88,39): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
(are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(206,40): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(304,40): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\Utility\DevCenterCredentialsHandler.cs(325,48): error CS0246: The type or namespace name 'AuthorizationHandlerCredentials' could not be found
 (are you missing a using directive or an assembly reference?) [C:\TDT\SDCM-1.2024.911.1\SDCM-1.2024.911.1\SurfaceDevCenterManager\SurfaceDevCenterManager.csproj]
    0 Warning(s)
    27 Error(s)

Time Elapsed 00:00:00.58

**Comment by Ben-Carpenter** [comment]
> Devices

For the assembly reference, I'm not sure why you are not able to obtain the packages from `NuGet`. How were you able to build the previous version?

**Comment by fdagnew** [comment]
Build it using visual studio 2022 and .net 4.7.1. [1.2024.911.1](https://github.com/microsoft/SDCM/releases/tag/1.2024.911.1) fixed my issue.

Thanks again

**Comment by Ben-Carpenter** [comment]
@fdagnew, glad to hear you were able to build and proceed with successful calls. I'll close this issue now.
