### ISSUE TITLE
I can't get all products and not all submission's downloads contain "drivermetadata"

### ISSUE THREAD

**Issue by hatasum** [Microsoft/SDCM#9]
I have two questions:
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-all-products
First question, my company are over 10000 products.
I use Get all products API, only can get 8910 products.
At last times, the service shows the error : "500 - Internal Server Error".

Second question, not all submission's downloads link contain "drivermetadata".
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-shipping-label
In create a shipping label, how can I get all hardwareIDs and boundle ID list to publish all ?
Thank you.

**Comment by hatasum** [comment]
I have a product which contains 3 inf files : Netwtw04.inf、Netwtw06.inf、Netwtw08.inf.
After call createMetadata API, I download drivermetadata from submission's link, it only contains "Netwtw04.inf".
Could you give me some suggestion?
Thank you.

**Comment by sfudally** [comment]
Unless those are extension INFs, I suggest splitting it up into 3 different products.  I avoid mixing multiple INFs together whenever possible.

**Comment by hatasum** [comment]
On Hardware Dashboard website, every SubmissionID will show hardwareids in each inf file, even the SID has lots of inf files.
as above mentioned, there are there inf files in SID, the web site will show HWIds in each Netwtw04.inf、Netwtw06.inf、Netwtw08.inf.
but I download drivermetadata from submission's link, it only contains HWIds in "Netwtw04.inf".

Could you help me how to get HWIds in "all" inf files like website?

**Comment by hatasum** [comment]
We found that "no HWIds" in Netwtw04.inf, it will not parser another inf files.
We try another SID has multiple inf files to create metadata, it is succeed to get all HWIds in all inf files.
